version: '3'

services: 
    app:
      build: .
      container_name: app
      entrypoint: dockerize -template ./.docker/app/.env:.env dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
      volumes:
        - .:/var/www
      environment: 
        - DB_HOST=db
        - DB_DATABASE=laravel
        - DB_USERNAME=root
        - DB_PASSWORD=root
      networks: 
        - app-network
      depends_on: 
        - db
        - redis
        
    nginx: 
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
          - "8000:80"
        volumes:
          - .:/var/www
        networks: 
          - app-network
        depends_on: 
          - app

    db: 
      image: mysql:5.7
      # command: --inodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes: 
        - ./.docker/datadir:/var/lib/mysql
      ports: 
        - "3306:3306"
      environment: 
        - MYSQL_DATABASE=laravel
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
      networks: 
        - app-network
      #healthcheck: 
      #  test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      #  interval: 10s
      #  timeout: 10s
      #  retries: 4 // ESSES RECURSOS NÃO ESTÃO MAIS DISPONÍVEIS NA VERSÃO 3 DO DOCKER-COMPOSE
        
    redis: 
        image: redis:alpine
        expose: 
          - 6379
        networks: 
          - app-network

networks: 
  app-network:
    driver: bridge